package io.agentflow.api;

import com.fasterxml.jackson.databind.JsonNode;
import io.agentflow.auth.AuthService;
import io.agentflow.common.JsonUtil;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping;

import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.Arrays;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * 对照实际 Spring 路由与请求记录类型，新增接口或字段不能默默遗漏契约。
 * @author owlzhangfq@gmail.com
 */
@SpringBootTest(properties = {"spring.datasource.url=jdbc:h2:mem:openapi-contract;DB_CLOSE_DELAY=-1", "agentflow.auth.demo-enabled=true"})
@AutoConfigureMockMvc
class OpenApiContractTest {
    @Autowired MockMvc mvc;
    @Autowired AuthService auth;
    @Autowired JsonUtil json;
    @Autowired @Qualifier("requestMappingHandlerMapping") RequestMappingHandlerMapping mappings;

    private JsonNode document() throws Exception {
        try (var in = new ClassPathResource("api/openapi.json").getInputStream()) {
            return json.read(new String(in.readAllBytes(), StandardCharsets.UTF_8), JsonNode.class);
        }
    }

    @Test
    void operationsExactlyMatchActualApiRoutesAndRequestFields() throws Exception {
        JsonNode spec = document();
        Set<String> actual = new HashSet<>();
        mappings.getHandlerMethods().forEach((mapping, handler) -> {
            for (String path : mapping.getPatternValues()) {
                if (!path.startsWith("/api/v1/")) continue;
                for (var method : mapping.getMethodsCondition().getMethods()) {
                    actual.add(method.name().toLowerCase() + " " + path);
                    JsonNode operation = spec.path("paths").path(path).path(method.name().toLowerCase());
                    assertThat(operation.isMissingNode()).as("contract for %s %s", method, path).isFalse();
                    for (var param : handler.getMethod().getParameters()) {
                        if (param.getAnnotation(RequestBody.class) == null || !param.getType().isRecord()) continue;
                        JsonNode schema = resolve(spec, operation.path("requestBody").path("content").path("application/json").path("schema"));
                        Set<String> fields = new HashSet<>(); schema.path("properties").fieldNames().forEachRemaining(fields::add);
                        assertThat(fields).as("request fields for %s", path).isEqualTo(Arrays.stream(param.getType().getRecordComponents())
                                .map(java.lang.reflect.RecordComponent::getName).collect(Collectors.toSet()));
                    }
                }
            }
        });
        Set<String> documented = new HashSet<>();
        spec.path("paths").fields().forEachRemaining(path -> path.getValue().fieldNames()
                .forEachRemaining(method -> documented.add(method + " " + path.getKey())));
        assertThat(documented).isEqualTo(actual);
    }

    @Test
    void riskRequiredFieldsMatchActualSerializationIncludingUnassessedLegacyRounds() throws Exception {
        var schema = document().path("components").path("schemas").path("SubmissionRisk");
        var classified = io.agentflow.approval.model.SubmissionRisk.assessed(java.util.UUID.randomUUID(), 1,
                java.util.List.of(new io.agentflow.approval.model.SubmissionRisk.Match("large", "公开规则", io.agentflow.approval.model.SubmissionRisk.Level.HIGH)));
        for (var risk : java.util.List.of(classified, io.agentflow.approval.model.SubmissionRisk.unassessed())) {
            JsonNode actual = json.read(json.write(risk), JsonNode.class);
            schema.path("required").forEach(field -> assertThat(actual.has(field.asText()))
                    .as("Required risk field %s for %s", field.asText(), risk.level()).isTrue());
            assertThat(actual.has("payload")).isFalse();
            assertThat(actual.has("condition")).isFalse();
        }
    }

    @Test
    void responseSchemasMatchPublishedRecordFields() throws Exception {
        JsonNode spec = document();
        // ResponseEntity<String> 的真实 JSON 来自业务 DTO，不能把它描述为普通字符串。
        var types = java.util.Map.ofEntries(
                java.util.Map.entry("ExpenseSplitRoutingView", io.agentflow.expense.ExpenseSplitRoutingQueries.View.class),
                java.util.Map.entry("InvoiceOccupationReference", io.agentflow.expense.InvoiceOccupationQueries.ExpenseReference.class),
                java.util.Map.entry("InvoiceOccupationView", io.agentflow.expense.InvoiceOccupationQueries.View.class),
                java.util.Map.entry("ExpenseInvoiceConflict", io.agentflow.expense.InvoiceOccupationQueries.Conflict.class),
                java.util.Map.entry("ExpenseSplitSnapshot", io.agentflow.expense.ExpenseSplitRoutingSnapshot.class),
                java.util.Map.entry("ExpenseSplitConfiguration", io.agentflow.expense.ExpenseSplitRiskPolicy.Configuration.class),
                java.util.Map.entry("ExpenseSplitRule", io.agentflow.expense.ExpenseSplitRiskPolicy.Rule.class),
                java.util.Map.entry("ExpenseSplitScope", io.agentflow.expense.ExpenseSplitRiskEvidence.Scope.class),
                java.util.Map.entry("ExpenseSplitLine", io.agentflow.expense.ExpenseSplitRiskEvidence.Line.class),
                java.util.Map.entry("ExpenseSplitDocument", io.agentflow.expense.ExpenseSplitRiskEvidence.Document.class),
                java.util.Map.entry("ExpenseSplitCategory", io.agentflow.expense.ExpenseSplitRiskEvidence.CategoryTotal.class),
                java.util.Map.entry("ExpenseSplitAssessment", io.agentflow.expense.ExpenseSplitRiskEvidence.Assessment.class),
                java.util.Map.entry("ExpenseRiskDocumentRequest", io.agentflow.agent.ExpenseRiskController.DocumentRequest.class),
                java.util.Map.entry("ExpenseRiskCalendar", io.agentflow.agent.ExpenseRiskAccess.CalendarOption.class),
                java.util.Map.entry("ExpenseRiskCalendars", io.agentflow.agent.ExpenseRiskAccess.CalendarOptions.class),
                java.util.Map.entry("ExpenseRiskScope", io.agentflow.agent.ExpenseRiskController.ScopeRequest.class),
                java.util.Map.entry("ExpenseRiskConcern", io.agentflow.agent.ExpenseRiskInput.Concern.class),
                java.util.Map.entry("ExpenseRiskInputOptions", io.agentflow.agent.ExpenseRiskService.InputOptions.class),
                java.util.Map.entry("ExpenseRiskReceipt", io.agentflow.agent.ExpenseRiskService.Receipt.class),
                java.util.Map.entry("ExpenseRiskSummary", io.agentflow.agent.JdbcExpenseRiskRepository.Summary.class),
                java.util.Map.entry("ExpenseRiskPage", io.agentflow.agent.JdbcExpenseRiskRepository.Page.class),
                java.util.Map.entry("ExpenseRiskDetail", io.agentflow.agent.ExpenseRiskService.Detail.class),
                java.util.Map.entry("ExpenseRiskItem", io.agentflow.agent.ExpenseRiskSuggestion.Item.class),
                java.util.Map.entry("ExpenseRiskSuggestion", io.agentflow.agent.ExpenseRiskSuggestion.class),
                java.util.Map.entry("ExpenseRiskReview", io.agentflow.agent.ExpenseRiskRun.Review.class),
                java.util.Map.entry("SignatureOptions", io.agentflow.signature.SignaturePublicService.Options.class),
                java.util.Map.entry("SignatureProfileOption", io.agentflow.signature.SignaturePublicService.ProfileOption.class),
                java.util.Map.entry("SignatureReceipt", io.agentflow.signature.SignaturePublicService.Receipt.class),
                java.util.Map.entry("SignaturePage", io.agentflow.signature.SignaturePublicService.Page.class),
                java.util.Map.entry("SignatureView", io.agentflow.signature.SignaturePublicService.View.class),
                java.util.Map.entry("SignatureDocumentView", io.agentflow.signature.SignaturePublicService.DocumentView.class),
                java.util.Map.entry("SignatureCallbackEnvelope", io.agentflow.signature.SignatureReceiptVerifier.Envelope.class),
                java.util.Map.entry("SignatureProviderReceipt", io.agentflow.signature.SignatureReceipt.class),
                java.util.Map.entry("SignatureArtifact", io.agentflow.signature.SignatureReceipt.Artifact.class),
                java.util.Map.entry("SignatureProof", io.agentflow.signature.SignatureReceipt.Proof.class),
                java.util.Map.entry("OrganizationSyncOverview", io.agentflow.organization.OrganizationSyncService.Overview.class),
                java.util.Map.entry("OrganizationSyncReceipt", io.agentflow.organization.OrganizationSyncService.Receipt.class),
                java.util.Map.entry("OrganizationSyncRequest", io.agentflow.organization.OrganizationSyncService.Request.class),
                java.util.Map.entry("OrganizationSyncDetail", io.agentflow.organization.OrganizationSyncService.Detail.class),
                java.util.Map.entry("OrganizationSyncState", io.agentflow.organization.OrganizationSyncBatch.State.class),
                java.util.Map.entry("OrganizationSyncApplied", io.agentflow.organization.OrganizationSyncBatch.Applied.class),
                java.util.Map.entry("OrganizationSyncDecision", io.agentflow.organization.OrganizationSyncBatch.Decision.class),
                java.util.Map.entry("OrganizationSyncKey", io.agentflow.organization.OrganizationSyncKey.class),
                java.util.Map.entry("OrganizationSyncDelta", io.agentflow.organization.OrganizationSyncDelta.class),
                java.util.Map.entry("OrganizationSyncDeltaUnit", io.agentflow.organization.OrganizationSyncDelta.Unit.class),
                java.util.Map.entry("OrganizationSyncDeltaPerson", io.agentflow.organization.OrganizationSyncDelta.Person.class),
                java.util.Map.entry("OrganizationSyncDeltaAppointment", io.agentflow.organization.OrganizationSyncDelta.Appointment.class),
                java.util.Map.entry("OrganizationSyncSummary", io.agentflow.organization.JdbcOrganizationSyncRepository.Summary.class),
                java.util.Map.entry("OrganizationSyncPage", io.agentflow.organization.JdbcOrganizationSyncRepository.Page.class),
                java.util.Map.entry("OrganizationSyncTransition", io.agentflow.organization.JdbcOrganizationSyncRepository.Transition.class),
                java.util.Map.entry("OrganizationSyncSelection", io.agentflow.organization.OrganizationSyncPlan.Selection.class),
                java.util.Map.entry("OrganizationSyncUnitChange", io.agentflow.organization.OrganizationSyncPlan.Change.class),
                java.util.Map.entry("OrganizationSyncPersonChange", io.agentflow.organization.OrganizationSyncPlan.Change.class),
                java.util.Map.entry("OrganizationSyncAppointmentChange", io.agentflow.organization.OrganizationSyncPlan.Change.class),
                java.util.Map.entry("OrganizationSyncConflict", io.agentflow.organization.OrganizationSyncPlan.Conflict.class),
                java.util.Map.entry("OrganizationSyncPlan", io.agentflow.organization.OrganizationSyncPlan.class),
                java.util.Map.entry("OrganizationSyncSavedPlan", io.agentflow.organization.JdbcOrganizationSyncPlanRepository.Saved.class),
                java.util.Map.entry("OrganizationSyncPlanSummary", io.agentflow.organization.JdbcOrganizationSyncPlanRepository.Summary.class),
                java.util.Map.entry("OrganizationSyncPlanPage", io.agentflow.organization.JdbcOrganizationSyncPlanRepository.Page.class),
                java.util.Map.entry("OrganizationSyncPlanReceipt", io.agentflow.organization.OrganizationSyncController.PlanReceipt.class),
                java.util.Map.entry("ExpensePolicyGuidance", io.agentflow.expense.ExpensePolicyGuidance.class),
                java.util.Map.entry("ExpensePolicyGuidanceContext", io.agentflow.expense.ExpensePolicyGuidance.Context.class),
                java.util.Map.entry("ExpensePolicyGuidanceView", io.agentflow.expense.ExpensePolicyGuidanceService.View.class),
                java.util.Map.entry("AdvanceOffsetSuggestion", io.agentflow.expense.AdvanceOffsetSuggestionService.Suggestion.class),
                java.util.Map.entry("AdvanceOffsetSuggestionItem", io.agentflow.expense.AdvanceOffsetSuggestionService.Item.class),
                java.util.Map.entry("ExpenseRequestClose", io.agentflow.expense.ExpenseRequestClosureController.CloseRequest.class),
                java.util.Map.entry("ExpenseRequestCloseReceipt", io.agentflow.expense.ExpenseRequestClosureService.Receipt.class),
                java.util.Map.entry("InvoiceExtractionInput", io.agentflow.agent.InvoiceExtractionInput.class),
                java.util.Map.entry("InvoiceExtractionInputOptions", io.agentflow.agent.InvoiceExtractionService.InputOptions.class),
                java.util.Map.entry("InvoiceExtractionSelection", io.agentflow.agent.InvoiceExtractionController.SelectionRequest.class),
                java.util.Map.entry("InvoiceExtractionEvidence", io.agentflow.agent.InvoiceExtractionSuggestion.Evidence.class),
                java.util.Map.entry("InvoiceExtractionProposal", io.agentflow.agent.InvoiceExtractionSuggestion.Proposal.class),
                java.util.Map.entry("InvoiceExtractionSuggestion", io.agentflow.agent.InvoiceExtractionSuggestion.class),
                java.util.Map.entry("InvoiceExtractionReview", io.agentflow.agent.InvoiceExtractionRun.Review.class),
                java.util.Map.entry("InvoiceExtractionReceipt", io.agentflow.agent.InvoiceExtractionService.Receipt.class),
                java.util.Map.entry("InvoiceExtractionSummary", io.agentflow.agent.JdbcInvoiceExtractionRunRepository.Summary.class),
                java.util.Map.entry("InvoiceExtractionPage", io.agentflow.agent.JdbcInvoiceExtractionRunRepository.Page.class),
                java.util.Map.entry("InvoiceExtractionDetail", io.agentflow.agent.InvoiceExtractionService.Detail.class),
                java.util.Map.entry("DraftAssistSelection", io.agentflow.agent.DraftSuggestion.Selection.class),
                java.util.Map.entry("DraftAssistProposal", io.agentflow.agent.DraftSuggestion.Proposal.class),
                java.util.Map.entry("DraftAssistSuggestion", io.agentflow.agent.DraftSuggestion.class),
                java.util.Map.entry("DraftAssistReview", io.agentflow.agent.DraftAssistRun.Review.class),
                java.util.Map.entry("DraftAssistReceipt", io.agentflow.agent.DraftAssistService.Receipt.class),
                java.util.Map.entry("DraftAssistInputOptions", io.agentflow.agent.DraftAssistService.InputOptions.class),
                java.util.Map.entry("DraftAssistSummary", io.agentflow.agent.JdbcDraftAssistRunRepository.Summary.class),
                java.util.Map.entry("DraftAssistPage", io.agentflow.agent.JdbcDraftAssistRunRepository.Page.class),
                java.util.Map.entry("DraftAssistDetail", io.agentflow.agent.DraftAssistService.Detail.class),
                java.util.Map.entry("PrecheckExplanationInputOptions", io.agentflow.agent.PrecheckExplanationService.InputOptions.class),
                java.util.Map.entry("PrecheckExplanationReceipt", io.agentflow.agent.PrecheckExplanationService.Receipt.class),
                java.util.Map.entry("PrecheckExplanationDetail", io.agentflow.agent.PrecheckExplanationService.Detail.class),
                java.util.Map.entry("PrecheckExplanationSummary", io.agentflow.agent.JdbcPrecheckExplanationRepository.Summary.class),
                java.util.Map.entry("PrecheckExplanationPage", io.agentflow.agent.JdbcPrecheckExplanationRepository.Page.class),
                java.util.Map.entry("PrecheckExplanationSuggestion", io.agentflow.agent.PrecheckExplanationSuggestion.class),
                java.util.Map.entry("PrecheckExplanationItem", io.agentflow.agent.PrecheckExplanationSuggestion.Item.class),
                java.util.Map.entry("PrecheckExplanationReview", io.agentflow.agent.PrecheckExplanationRun.Review.class),
                java.util.Map.entry("FormAssigneeOption", io.agentflow.definition.DefinitionAssigneeDirectory.FormOption.class),
                java.util.Map.entry("ApprovalProxy", io.agentflow.organization.ApprovalProxy.class),
                java.util.Map.entry("ApprovalProxyOption", io.agentflow.approval.process.FlowableApprovalProxyAccess.Option.class),
                java.util.Map.entry("ApprovalProxyUse", io.agentflow.organization.ApprovalProxyUse.class),
                java.util.Map.entry("ApprovalProxyRevocation", io.agentflow.organization.ApprovalProxy.Revocation.class),
                java.util.Map.entry("ApprovalProxyReceipt", io.agentflow.organization.ApprovalProxyController.Receipt.class),
                java.util.Map.entry("ApprovalProxyView", io.agentflow.organization.ApprovalProxyController.View.class),
                java.util.Map.entry("ApprovalProxyPerson", io.agentflow.organization.ApprovalProxyController.Person.class),
                java.util.Map.entry("ApprovalProxyPage", io.agentflow.organization.ApprovalProxyController.Page.class),
                java.util.Map.entry("TenantInitialization", io.agentflow.onboarding.TenantInitialization.class),
                java.util.Map.entry("TenantInitializationState", io.agentflow.onboarding.TenantInitializationService.State.class),
                java.util.Map.entry("InitializationChannelBinding", io.agentflow.onboarding.TenantInitializationService.ChannelBinding.class),
                java.util.Map.entry("InitializationOrganizationChoice", io.agentflow.onboarding.InitializationRequest.OrganizationChoice.class),
                java.util.Map.entry("InitializationCalendarChoice", io.agentflow.onboarding.InitializationRequest.CalendarChoice.class),
                java.util.Map.entry("InitializationNotificationChoice", io.agentflow.onboarding.InitializationRequest.NotificationChoice.class),
                java.util.Map.entry("InitializationNotificationSnapshot", io.agentflow.notification.NotificationPreferences.class),
                java.util.Map.entry("InitializationCalendarSnapshot", io.agentflow.calendar.BusinessCalendar.class),
                java.util.Map.entry("Graph", io.agentflow.definition.DefinitionModels.Graph.class),
                java.util.Map.entry("ApprovalRiskPolicy", io.agentflow.definition.ApprovalRiskPolicy.class),
                java.util.Map.entry("ApprovalRiskRule", io.agentflow.definition.ApprovalRiskPolicy.Rule.class),
                java.util.Map.entry("SubmissionRisk", io.agentflow.approval.model.SubmissionRisk.class),
                java.util.Map.entry("SubmissionRiskMatch", io.agentflow.approval.model.SubmissionRisk.Match.class),
                java.util.Map.entry("SubprocessRelationsPage", io.agentflow.approval.SubprocessRelationsService.Page.class),
                java.util.Map.entry("SubprocessRelationChild", io.agentflow.approval.SubprocessRelationsService.Child.class),
                java.util.Map.entry("SubprocessRoundReference", io.agentflow.approval.SubprocessRelationsService.Reference.class),
                java.util.Map.entry("InitiatorRequirements", io.agentflow.definition.DefinitionInitiatorRequirements.View.class),
                java.util.Map.entry("EventContractOption", io.agentflow.event.EventContractViews.Option.class),
                java.util.Map.entry("EventContractAvailability", io.agentflow.event.EventContractViews.Availability.class),
                java.util.Map.entry("EventContractDetail", io.agentflow.event.EventContractViews.Detail.class),
                java.util.Map.entry("EventContractDirectory", io.agentflow.event.EventContractViews.Directory.class),
                java.util.Map.entry("EventContractVersionPage", io.agentflow.event.EventContractViews.Versions.class),
                java.util.Map.entry("EventContractHistory", io.agentflow.event.EventContractViews.History.class),
                java.util.Map.entry("InstanceControlView", io.agentflow.approval.process.InstanceControlService.View.class),
                java.util.Map.entry("TimerWaitEntry", io.agentflow.approval.process.TimerWaitService.Entry.class),
                java.util.Map.entry("TimerWaitView", io.agentflow.approval.process.TimerWaitService.View.class),
                java.util.Map.entry("EventWaitEntry", io.agentflow.approval.process.EventWaitService.Entry.class),
                java.util.Map.entry("EventWaitView", io.agentflow.approval.process.EventWaitService.View.class),
                java.util.Map.entry("TimerWaitReceipt", io.agentflow.approval.process.TimerWaitService.Receipt.class),
                java.util.Map.entry("CountersignMember", io.agentflow.approval.process.CountersignMembershipService.Member.class),
                java.util.Map.entry("CountersignMembershipView", io.agentflow.approval.process.CountersignMembershipService.View.class),
                java.util.Map.entry("CountersignMembershipReceipt", io.agentflow.approval.process.CountersignMembershipService.Receipt.class),
                java.util.Map.entry("CountersignMembershipChange", io.agentflow.approval.service.TaskAuditPort.MembershipChange.class),
                java.util.Map.entry("SupplierAdjustmentDisputeView", io.agentflow.procurement.SupplierAdjustmentDisputeService.View.class),
                java.util.Map.entry("SupplierAdjustmentDisputeFact", io.agentflow.procurement.SupplierAdjustmentDisputeService.Fact.class),
                java.util.Map.entry("SupplierAdjustmentDisputePosting", io.agentflow.procurement.SupplierAdjustmentDisputeService.Posting.class),
                java.util.Map.entry("SupplierAdjustmentDisputeDecision", io.agentflow.procurement.SupplierAdjustmentDisputeService.Decision.class),
                java.util.Map.entry("SupplierAdjustmentDisputeReceipt", io.agentflow.procurement.SupplierAdjustmentDisputeService.Receipt.class),
                java.util.Map.entry("SupplierAdjustmentView", io.agentflow.procurement.SupplierAdjustmentWorkspace.View.class),
                java.util.Map.entry("SupplierAdjustmentBank", io.agentflow.procurement.SupplierAdjustmentWorkspace.Bank.class),
                java.util.Map.entry("SupplierAdjustmentPreparation", io.agentflow.procurement.SupplierAdjustmentWorkspace.Preparation.class),
                java.util.Map.entry("SupplierAdjustmentOperation", io.agentflow.procurement.SupplierAdjustmentWorkspace.Operation.class),
                java.util.Map.entry("SupplierAdjustmentPosting", io.agentflow.procurement.SupplierAdjustmentWorkspace.Posting.class),
                java.util.Map.entry("SupplierAdjustmentEntry", io.agentflow.procurement.SupplierAdjustmentWorkspace.Entry.class),
                java.util.Map.entry("SupplierAdjustmentRetirement", io.agentflow.procurement.SupplierAdjustmentWorkspace.Retirement.class),
                java.util.Map.entry("SupplierAdjustmentCompletion", io.agentflow.procurement.SupplierAdjustmentWorkspace.Completion.class),
                java.util.Map.entry("SupplierAdjustmentActions", io.agentflow.procurement.SupplierAdjustmentWorkspace.Actions.class),
                java.util.Map.entry("SupplierAdjustmentReceipt", io.agentflow.procurement.SupplierAdjustmentActions.Receipt.class),
                java.util.Map.entry("PaymentBatchSelection", io.agentflow.finance.PaymentBatchService.Selection.class),
                java.util.Map.entry("PaymentBatchReceipt", io.agentflow.finance.PaymentBatchService.Receipt.class),
                java.util.Map.entry("PaymentBatchSummary", io.agentflow.finance.PaymentBatchService.Summary.class),
                java.util.Map.entry("PaymentBatchItem", io.agentflow.finance.PaymentBatchService.Item.class),
                java.util.Map.entry("PaymentBatchDetail", io.agentflow.finance.PaymentBatchService.Detail.class),
                java.util.Map.entry("PaymentBatchPage", io.agentflow.finance.PaymentBatchService.Page.class),
                java.util.Map.entry("PaymentCallbackSignal", io.agentflow.finance.callback.PaymentCallbackVerifier.Signal.class),
                java.util.Map.entry("InboundEventSignal", io.agentflow.event.EventSignal.class),
                java.util.Map.entry("EventInboxReceipt", io.agentflow.event.EventInboxController.Receipt.class),
                java.util.Map.entry("EventInboxView", io.agentflow.event.EventInboxController.View.class),
                java.util.Map.entry("EventInboxPage", io.agentflow.event.EventInboxController.Page.class),
                java.util.Map.entry("EventInboxHistory", io.agentflow.event.EventInboxController.History.class),
                java.util.Map.entry("PaymentCallbackReceipt", io.agentflow.finance.callback.PaymentCallbackController.Receipt.class),
                java.util.Map.entry("PaymentCallbackView", io.agentflow.finance.callback.PaymentCallbackController.View.class),
                java.util.Map.entry("PaymentCallbackPage", io.agentflow.finance.callback.PaymentCallbackController.Page.class),
                java.util.Map.entry("PaymentCallbackDetail", io.agentflow.finance.callback.PaymentCallbackController.Detail.class),
                java.util.Map.entry("SupplierPaymentReturnView", io.agentflow.procurement.SupplierPaymentReturnWorkspace.View.class),
                java.util.Map.entry("SupplierPaymentReturnOriginal", io.agentflow.procurement.SupplierPaymentReturnWorkspace.Original.class),
                java.util.Map.entry("SupplierPaymentReturnFunding", io.agentflow.procurement.SupplierPaymentReturnWorkspace.Funding.class),
                java.util.Map.entry("SupplierPaymentReturnReturned", io.agentflow.procurement.SupplierPaymentReturnWorkspace.Returned.class),
                java.util.Map.entry("SupplierPaymentReturnCheck", io.agentflow.procurement.SupplierPaymentReturnWorkspace.Check.class),
                java.util.Map.entry("SupplierPaymentReturnEvidence", io.agentflow.procurement.SupplierPaymentReturnWorkspace.Evidence.class),
                java.util.Map.entry("SupplierPaymentReturnRegistration", io.agentflow.procurement.SupplierPaymentReturnWorkspace.Registration.class),
                java.util.Map.entry("SupplierPaymentReturnActionReceipt", io.agentflow.procurement.SupplierPaymentReturnService.ActionReceipt.class),
                java.util.Map.entry("SupplierDisputeView", io.agentflow.procurement.SupplierPaymentDisputeService.View.class),
                java.util.Map.entry("SupplierDisputeFact", io.agentflow.procurement.SupplierPaymentDisputeService.Fact.class),
                java.util.Map.entry("SupplierDisputeDecision", io.agentflow.procurement.SupplierPaymentDisputeService.Decision.class),
                java.util.Map.entry("SupplierDisputeReceipt", io.agentflow.procurement.SupplierPaymentDisputeService.Receipt.class),
                java.util.Map.entry("SupplierSettlementDisputeView", io.agentflow.procurement.SupplierSettlementDisputeService.View.class),
                java.util.Map.entry("SupplierSettlementDisputeFact", io.agentflow.procurement.SupplierSettlementDisputeService.Fact.class),
                java.util.Map.entry("SupplierSettlementDisputePosting", io.agentflow.procurement.SupplierSettlementDisputeService.Posting.class),
                java.util.Map.entry("SupplierSettlementDisputeDecision", io.agentflow.procurement.SupplierSettlementDisputeService.Decision.class),
                java.util.Map.entry("SupplierSettlementDisputeReceipt", io.agentflow.procurement.SupplierSettlementDisputeService.Receipt.class),
                java.util.Map.entry("SupplierSettlementView", io.agentflow.procurement.SupplierSettlementWorkspace.View.class),
                java.util.Map.entry("SupplierSettlementBank", io.agentflow.procurement.SupplierSettlementWorkspace.Bank.class),
                java.util.Map.entry("SupplierSettlementPreparation", io.agentflow.procurement.SupplierSettlementWorkspace.Preparation.class),
                java.util.Map.entry("SupplierSettlementOperation", io.agentflow.procurement.SupplierSettlementWorkspace.Operation.class),
                java.util.Map.entry("SupplierSettlementPosting", io.agentflow.procurement.SupplierSettlementWorkspace.Posting.class),
                java.util.Map.entry("SupplierSettlementRetirement", io.agentflow.procurement.SupplierSettlementWorkspace.Retirement.class),
                java.util.Map.entry("SupplierSettlementCompletion", io.agentflow.procurement.SupplierSettlementWorkspace.Completion.class),
                java.util.Map.entry("SupplierSettlementActions", io.agentflow.procurement.SupplierSettlementWorkspace.Actions.class),
                java.util.Map.entry("SupplierSettlementReceipt", io.agentflow.procurement.SupplierSettlementActions.Receipt.class),
                java.util.Map.entry("SupplierCashierView", io.agentflow.procurement.SupplierCashierWorkspace.View.class),
                java.util.Map.entry("SupplierCashierPage", io.agentflow.procurement.SupplierCashierWorkspace.Page.class),
                java.util.Map.entry("SupplierCashierHold", io.agentflow.procurement.SupplierCashierWorkspace.Hold.class),
                java.util.Map.entry("SupplierCashierPreparation", io.agentflow.procurement.SupplierCashierWorkspace.Preparation.class),
                java.util.Map.entry("SupplierCashierOperation", io.agentflow.procurement.SupplierCashierWorkspace.Operation.class),
                java.util.Map.entry("SupplierCashierActions", io.agentflow.procurement.SupplierCashierWorkspace.Actions.class),
                java.util.Map.entry("SupplierCashierAccounts", io.agentflow.procurement.SupplierCashierWorkspace.Accounts.class),
                java.util.Map.entry("SupplierCashierReceipt", io.agentflow.procurement.SupplierCashierActions.Receipt.class),
                java.util.Map.entry("SupplierFinanceWorkspace", io.agentflow.procurement.SupplierFinanceWorkspace.View.class),
                java.util.Map.entry("SupplierFinanceReview", io.agentflow.procurement.SupplierFinanceWorkspace.Review.class),
                java.util.Map.entry("SupplierFinanceAuthorization", io.agentflow.procurement.SupplierFinanceWorkspace.Authorization.class),
                java.util.Map.entry("SupplierFinanceHold", io.agentflow.procurement.SupplierFinanceWorkspace.Hold.class),
                java.util.Map.entry("SupplierFinanceActions", io.agentflow.procurement.SupplierFinanceWorkspace.Actions.class),
                java.util.Map.entry("SupplierFinanceReceipt", io.agentflow.procurement.SupplierFinanceActions.Receipt.class),
                java.util.Map.entry("BudgetAdjustmentFinanceWorkspace", io.agentflow.budget.BudgetAdjustmentFinanceWorkspace.View.class),
                java.util.Map.entry("BudgetAdjustmentFinanceReview", io.agentflow.budget.BudgetAdjustmentFinanceWorkspace.ReviewView.class),
                java.util.Map.entry("BudgetAdjustmentFinanceOperation", io.agentflow.budget.BudgetAdjustmentFinanceWorkspace.OperationView.class),
                java.util.Map.entry("BudgetAdjustmentFinanceResult", io.agentflow.budget.BudgetAdjustmentFinanceWorkspace.ResultView.class),
                java.util.Map.entry("BudgetAdjustmentFinanceRetirement", io.agentflow.budget.BudgetAdjustmentRetirement.class),
                java.util.Map.entry("BudgetAdjustmentFinanceActions", io.agentflow.budget.BudgetAdjustmentFinanceWorkspace.Actions.class),
                java.util.Map.entry("BudgetAdjustmentFinancePage", io.agentflow.budget.BudgetAdjustmentFinanceWorkspace.Page.class),
                java.util.Map.entry("BudgetAdjustmentFinanceReceipt", io.agentflow.budget.BudgetAdjustmentFinanceActions.Receipt.class),
                java.util.Map.entry("BudgetAdjustmentContent", io.agentflow.budget.BudgetAdjustmentContent.class),
                java.util.Map.entry("BudgetAdjustmentRound", io.agentflow.budget.BudgetAdjustmentRoundView.class),
                java.util.Map.entry("BudgetAdjustmentView", io.agentflow.budget.BudgetAdjustmentService.View.class),
                java.util.Map.entry("BudgetAdjustmentReceipt", io.agentflow.budget.BudgetAdjustmentService.Receipt.class),
                java.util.Map.entry("BudgetAdjustmentItem", io.agentflow.budget.BudgetAdjustmentQuery.Item.class),
                java.util.Map.entry("BudgetAdjustmentPage", io.agentflow.budget.BudgetAdjustmentQuery.Page.class),
                java.util.Map.entry("BudgetAdjustmentApproval", io.agentflow.budget.BudgetAdjustmentRequest.Approval.class),
                java.util.Map.entry("BudgetAdjustmentCheckOptions", io.agentflow.budget.BudgetAdjustmentCheckService.Options.class),
                java.util.Map.entry("BudgetAdjustmentCheckSummary", io.agentflow.budget.BudgetAdjustmentCheckService.Summary.class),
                java.util.Map.entry("BudgetAdjustmentCheckPage", io.agentflow.budget.BudgetAdjustmentCheckService.Page.class),
                java.util.Map.entry("BudgetAdjustmentCheckReceipt", io.agentflow.budget.BudgetAdjustmentCheckService.Receipt.class),
                java.util.Map.entry("BudgetAdjustmentCheckView", io.agentflow.budget.BudgetAdjustmentCheckService.View.class),
                java.util.Map.entry("BudgetAdjustmentPosition", io.agentflow.budget.BudgetAdjustmentRoundView.PositionView.class),
                java.util.Map.entry("ProcurementPaymentContent", io.agentflow.procurement.ProcurementPaymentContent.class),
                java.util.Map.entry("ProcurementPaymentRound", io.agentflow.procurement.ProcurementPaymentRoundView.class),
                java.util.Map.entry("ProcurementPaymentPayable", io.agentflow.procurement.ProcurementPaymentRoundView.PayableView.class),
                java.util.Map.entry("ProcurementPaymentLine", io.agentflow.procurement.ProcurementPaymentRoundView.LineView.class),
                java.util.Map.entry("ProcurementPaymentView", io.agentflow.procurement.ProcurementPaymentService.View.class),
                java.util.Map.entry("ProcurementPaymentReceipt", io.agentflow.procurement.ProcurementPaymentService.Receipt.class),
                java.util.Map.entry("ProcurementPaymentItem", io.agentflow.procurement.ProcurementPaymentQuery.Item.class),
                java.util.Map.entry("ProcurementPaymentPage", io.agentflow.procurement.ProcurementPaymentQuery.Page.class),
                java.util.Map.entry("ProcurementPaymentApproval", io.agentflow.procurement.ProcurementPaymentRequest.Approval.class),
                java.util.Map.entry("ProcurementPaymentCheckOptions", io.agentflow.procurement.ProcurementPaymentCheckService.Options.class),
                java.util.Map.entry("ProcurementPaymentCheckSummary", io.agentflow.procurement.ProcurementPaymentCheckService.Summary.class),
                java.util.Map.entry("ProcurementPaymentCheckPage", io.agentflow.procurement.ProcurementPaymentCheckService.Page.class),
                java.util.Map.entry("ProcurementPaymentCheckReceipt", io.agentflow.procurement.ProcurementPaymentCheckService.Receipt.class),
                java.util.Map.entry("ProcurementPaymentCheckView", io.agentflow.procurement.ProcurementPaymentCheckService.View.class),
                java.util.Map.entry("ExpenseResourceAdjustmentWorkspace", io.agentflow.expense.ExpenseResourceAdjustmentWorkspace.View.class),
                java.util.Map.entry("ExpensePartialActionReceipt", io.agentflow.expense.ExpensePartialAdjustmentAudit.Receipt.class),
                java.util.Map.entry("ExpensePartialWorkspace", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.View.class),
                java.util.Map.entry("ExpensePartialOriginal", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Original.class),
                java.util.Map.entry("ExpensePartialSource", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Source.class),
                java.util.Map.entry("ExpensePartialAmounts", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Amounts.class),
                java.util.Map.entry("ExpensePartialLine", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Line.class),
                java.util.Map.entry("ExpensePartialReturnEntry", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.ReturnEntry.class),
                java.util.Map.entry("ExpensePartialPreparation", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Preparation.class),
                java.util.Map.entry("ExpensePartialAdjustment", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Adjustment.class),
                java.util.Map.entry("ExpensePartialBudget", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Budget.class),
                java.util.Map.entry("ExpensePartialBudgetFact", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.BudgetFact.class),
                java.util.Map.entry("ExpensePartialAccrual", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Accrual.class),
                java.util.Map.entry("ExpensePartialAccrualFact", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.AccrualFact.class),
                java.util.Map.entry("ExpensePartialCompletion", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Completion.class),
                java.util.Map.entry("ExpensePartialRetirement", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Retirement.class),
                java.util.Map.entry("ExpensePartialResolution", io.agentflow.expense.ExpensePartialAdjustmentWorkspace.Resolution.class),
                java.util.Map.entry("ExpenseResourceAdjustmentOriginal", io.agentflow.expense.ExpenseResourceAdjustmentWorkspace.Original.class),
                java.util.Map.entry("ExpenseResourceAdjustmentPreparation", io.agentflow.expense.ExpenseResourceAdjustmentWorkspace.Preparation.class),
                java.util.Map.entry("ExpenseResourceAdjustmentBudget", io.agentflow.expense.ExpenseResourceAdjustmentWorkspace.Budget.class),
                java.util.Map.entry("ExpenseResourceAdjustmentRetirement", io.agentflow.expense.ExpenseResourceAdjustmentWorkspace.Retirement.class),
                java.util.Map.entry("ExpenseResourceAdjustmentEntry", io.agentflow.expense.ExpenseResourceAdjustmentWorkspace.Adjustment.class),
                java.util.Map.entry("ExpenseResourceAdjustmentPreparationReceipt", io.agentflow.expense.ExpenseResourceAdjustmentPreparationService.ActionReceipt.class),
                java.util.Map.entry("ExpenseResourceAdjustmentActionReceipt", io.agentflow.expense.ExpenseResourceAdjustmentActionService.ActionReceipt.class),
                java.util.Map.entry("PaymentView", io.agentflow.finance.PaymentView.class),
                java.util.Map.entry("PaymentRequestSummary", io.agentflow.finance.PaymentView.Request.class),
                java.util.Map.entry("PaymentOperationSummary", io.agentflow.finance.PaymentView.Operation.class),
                java.util.Map.entry("FinancePaymentWorkspace", io.agentflow.finance.FinancePaymentWorkspace.View.class),
                java.util.Map.entry("FinancePaymentActions", io.agentflow.finance.FinancePaymentWorkspace.Actions.class),
                java.util.Map.entry("PaymentRetirement", io.agentflow.finance.PaymentView.Retirement.class),
                java.util.Map.entry("PaymentPayeeReview", io.agentflow.finance.FinancePaymentWorkspace.PayeeReview.class),
                java.util.Map.entry("PaymentPayeeReviewReceipt", io.agentflow.finance.FinancePaymentActions.ReviewReceipt.class),
                java.util.Map.entry("VoucherReversalWorkspace", io.agentflow.finance.VoucherReversalWorkspace.View.class),
                java.util.Map.entry("VoucherReversalOriginal", io.agentflow.finance.VoucherReversalWorkspace.Original.class),
                java.util.Map.entry("VoucherReversalCheck", io.agentflow.finance.VoucherReversalWorkspace.Check.class),
                java.util.Map.entry("VoucherReversalEvidence", io.agentflow.finance.VoucherReversalWorkspace.Evidence.class),
                java.util.Map.entry("VoucherReversalRecorded", io.agentflow.finance.VoucherReversalWorkspace.Recorded.class),
                java.util.Map.entry("VoucherReversePosting", io.agentflow.finance.VoucherReversalPort.Posting.class),
                java.util.Map.entry("VoucherReversalLine", io.agentflow.finance.VoucherReversalPort.Line.class),
                java.util.Map.entry("VoucherReversalActionReceipt", io.agentflow.finance.VoucherReversalService.ActionReceipt.class),
                java.util.Map.entry("VoucherReversalCommandLine", io.agentflow.finance.VoucherReversalCommand.Line.class),
                java.util.Map.entry("VoucherReversalExecutionWorkspace", io.agentflow.finance.VoucherReversalExecutionWorkspace.View.class),
                java.util.Map.entry("VoucherReversalExecutionPreparation", io.agentflow.finance.VoucherReversalExecutionWorkspace.Preparation.class),
                java.util.Map.entry("VoucherReversalExecutionCandidate", io.agentflow.finance.VoucherReversalExecutionWorkspace.Candidate.class),
                java.util.Map.entry("VoucherReversalExecutionOperation", io.agentflow.finance.VoucherReversalExecutionWorkspace.Execution.class),
                java.util.Map.entry("VoucherReversalExecutionObservation", io.agentflow.finance.VoucherReversalExecutionWorkspace.Observation.class),
                java.util.Map.entry("VoucherReversalRetirementCheck", io.agentflow.finance.VoucherReversalExecutionWorkspace.RetirementCheck.class),
                java.util.Map.entry("VoucherReversalRetired", io.agentflow.finance.VoucherReversalExecutionWorkspace.Retired.class),
                java.util.Map.entry("VoucherReversalRetirementReceipt", io.agentflow.finance.VoucherReversalRetirementService.Receipt.class),
                java.util.Map.entry("VoucherReversalExecutionActionReceipt", io.agentflow.finance.VoucherReversalPreparationService.ActionReceipt.class),
                java.util.Map.entry("VoucherDisputeView", io.agentflow.finance.VoucherDisputeService.View.class),
                java.util.Map.entry("VoucherDisputeCandidate", io.agentflow.finance.VoucherDisputeService.Candidate.class),
                java.util.Map.entry("VoucherDisputeDecision", io.agentflow.finance.VoucherDisputeService.Decision.class),
                java.util.Map.entry("VoucherDisputeReceipt", io.agentflow.finance.VoucherDisputeService.Receipt.class),
                java.util.Map.entry("PaymentDisputeView", io.agentflow.finance.PaymentDisputeService.View.class),
                java.util.Map.entry("PaymentDisputeCandidate", io.agentflow.finance.PaymentDisputeService.Candidate.class),
                java.util.Map.entry("PaymentDisputeDecision", io.agentflow.finance.PaymentDisputeService.Decision.class),
                java.util.Map.entry("PaymentDisputeReceipt", io.agentflow.finance.PaymentDisputeService.Receipt.class),
                java.util.Map.entry("RepaymentReturnedFunds", io.agentflow.finance.AdvanceRepaymentAdjustmentPort.FundsReturn.class),
                java.util.Map.entry("RepaymentReturnPosting", io.agentflow.finance.AdvanceRepaymentAdjustmentPort.ReturnPosting.class),
                java.util.Map.entry("RepaymentReturn", io.agentflow.expense.AdvanceRepaymentResolution.ReturnEntry.class),
                java.util.Map.entry("RepaymentReviewWorkspace", io.agentflow.expense.AdvanceRepaymentReviewWorkspace.View.class),
                java.util.Map.entry("RepaymentReviewCheck", io.agentflow.expense.AdvanceRepaymentReviewWorkspace.Check.class),
                java.util.Map.entry("RepaymentReviewEvidence", io.agentflow.expense.AdvanceRepaymentReviewWorkspace.Evidence.class),
                java.util.Map.entry("RepaymentReviewDecision", io.agentflow.expense.AdvanceRepaymentReviewWorkspace.Decision.class),
                java.util.Map.entry("RepaymentReviewActionReceipt", io.agentflow.expense.AdvanceRepaymentReviewService.ActionReceipt.class),
                java.util.Map.entry("AdvanceRepaymentWorkspace", io.agentflow.expense.AdvanceRepaymentWorkspace.View.class),
                java.util.Map.entry("AdvanceRepaymentBalance", io.agentflow.expense.AdvanceRepaymentWorkspace.Balance.class),
                java.util.Map.entry("AdvanceRepaymentCheck", io.agentflow.expense.AdvanceRepaymentWorkspace.Check.class),
                java.util.Map.entry("AdvanceRepaymentEvidence", io.agentflow.expense.AdvanceRepaymentWorkspace.Evidence.class),
                java.util.Map.entry("AdvanceRepaymentFunding", io.agentflow.finance.AdvanceRepaymentPort.Funding.class),
                java.util.Map.entry("AdvanceRepaymentPosting", io.agentflow.finance.AdvanceRepaymentPort.Posting.class),
                java.util.Map.entry("AdvanceRepaymentRecord", io.agentflow.expense.AdvanceRepaymentWorkspace.Recorded.class),
                java.util.Map.entry("AdvanceRepaymentActionReceipt", io.agentflow.expense.AdvanceRepaymentService.ActionReceipt.class),
                java.util.Map.entry("FinancePaymentReceipt", io.agentflow.finance.FinancePaymentActions.Receipt.class),
                java.util.Map.entry("CashierPaymentWorkspace", io.agentflow.finance.CashierPaymentWorkspace.View.class),
                java.util.Map.entry("CashierPaymentActions", io.agentflow.finance.CashierPaymentWorkspace.Actions.class),
                java.util.Map.entry("CashierPaymentPage", io.agentflow.finance.CashierPaymentWorkspace.Page.class),
                java.util.Map.entry("CashierPaymentAccounts", io.agentflow.finance.CashierPaymentWorkspace.Accounts.class),
                java.util.Map.entry("PaymentDebitAccount", io.agentflow.finance.PaymentAccountsPort.DebitAccount.class),
                java.util.Map.entry("CashierPaymentReceipt", io.agentflow.finance.CashierPaymentActions.Receipt.class),
                java.util.Map.entry("VoucherWorkspace", io.agentflow.finance.VoucherWorkspace.View.class),
                java.util.Map.entry("VoucherMappingEvidence", io.agentflow.finance.VoucherWorkspace.MappingEvidence.class),
                java.util.Map.entry("VoucherPreparationSummary", io.agentflow.finance.VoucherWorkspace.Preparation.class),
                java.util.Map.entry("VoucherOperationSummary", io.agentflow.finance.VoucherWorkspace.Operation.class),
                java.util.Map.entry("VoucherActionOptions", io.agentflow.finance.VoucherWorkspace.Actions.class),
                java.util.Map.entry("VoucherActionReceipt", io.agentflow.finance.VoucherActions.Receipt.class),
                java.util.Map.entry("AdvanceRequestView", io.agentflow.expense.AdvanceRequestService.View.class),
                java.util.Map.entry("AdvanceRequestReceipt", io.agentflow.expense.AdvanceRequestService.Receipt.class),
                java.util.Map.entry("AdvanceRequestContent", io.agentflow.expense.AdvanceRequestContent.class),
                java.util.Map.entry("AdvanceRequestRound", io.agentflow.expense.AdvanceRequestRoundView.class),
                java.util.Map.entry("AdvanceRequestApproval", io.agentflow.expense.AdvanceRequest.Approval.class),
                java.util.Map.entry("AdvanceRequestItem", io.agentflow.expense.AdvanceRequestQuery.Item.class),
                java.util.Map.entry("AdvanceRequestPage", io.agentflow.expense.AdvanceRequestQuery.Page.class),
                java.util.Map.entry("AdvanceRequestCheckOptions", io.agentflow.expense.AdvanceRequestCheckService.Options.class),
                java.util.Map.entry("AdvanceRequestCheckSummary", io.agentflow.expense.AdvanceRequestCheckService.Summary.class),
                java.util.Map.entry("AdvanceRequestCheckReceipt", io.agentflow.expense.AdvanceRequestCheckService.Receipt.class),
                java.util.Map.entry("AdvanceRequestCheckPage", io.agentflow.expense.AdvanceRequestCheckService.Page.class),
                java.util.Map.entry("AdvanceRequestCheckView", io.agentflow.expense.AdvanceRequestCheckService.View.class),
                java.util.Map.entry("ExpensePlanView", io.agentflow.expense.ExpensePlanService.View.class),
                java.util.Map.entry("ExpensePlanReceipt", io.agentflow.expense.ExpensePlanService.Receipt.class),
                java.util.Map.entry("ExpensePlanContent", io.agentflow.expense.ExpensePlanContent.class),
                java.util.Map.entry("ExpensePlanLine", io.agentflow.expense.ExpensePlanContent.Line.class),
                java.util.Map.entry("ExpensePlanRound", io.agentflow.expense.ExpensePlanRound.class),
                java.util.Map.entry("ExpensePlanFrozenLine", io.agentflow.expense.ExpensePlanRound.FrozenLine.class),
                java.util.Map.entry("ExpensePlanItem", io.agentflow.expense.ExpensePlanQuery.Item.class),
                java.util.Map.entry("ExpensePlanPage", io.agentflow.expense.ExpensePlanQuery.Page.class),
                java.util.Map.entry("ExpensePlanCheckOptions", io.agentflow.expense.ExpensePlanCheckService.Options.class),
                java.util.Map.entry("ExpensePlanCheckSummary", io.agentflow.expense.ExpensePlanCheckService.Summary.class),
                java.util.Map.entry("ExpensePlanCheckReceipt", io.agentflow.expense.ExpensePlanCheckService.Receipt.class),
                java.util.Map.entry("ExpensePlanCheckPage", io.agentflow.expense.ExpensePlanCheckService.Page.class),
                java.util.Map.entry("ExpensePlanCheckView", io.agentflow.expense.ExpensePlanCheckService.View.class),
                java.util.Map.entry("ExpenseReportItem", io.agentflow.expense.ExpenseWorkspaceQuery.ReportItem.class),
                java.util.Map.entry("ExpenseReportPage", io.agentflow.expense.ExpenseWorkspaceQuery.ReportPage.class),
                java.util.Map.entry("ExpensePriorLine", io.agentflow.expense.ExpenseWorkspaceQuery.PriorLine.class),
                java.util.Map.entry("ExpensePriorItem", io.agentflow.expense.ExpenseWorkspaceQuery.PriorItem.class),
                java.util.Map.entry("ExpensePriorPage", io.agentflow.expense.ExpenseWorkspaceQuery.PriorPage.class),
                java.util.Map.entry("ExpenseAdvanceItem", io.agentflow.expense.ExpenseWorkspaceQuery.AdvanceItem.class),
                java.util.Map.entry("ExpenseAdvancePage", io.agentflow.expense.ExpenseWorkspaceQuery.AdvancePage.class),
                java.util.Map.entry("ExpenseWorkflow", io.agentflow.expense.ExpenseWorkflowQuery.View.class),
                java.util.Map.entry("ExpenseWorkflowPaper", io.agentflow.expense.ExpenseWorkflowQuery.Paper.class),
                java.util.Map.entry("ExpenseWorkflowBudget", io.agentflow.expense.ExpenseWorkflowQuery.Budget.class),
                java.util.Map.entry("ExpenseTaskOptions", io.agentflow.expense.ExpenseWorkflowQuery.TaskOptions.class),
                java.util.Map.entry("ExpenseReductionReceipt", io.agentflow.expense.ExpenseReductionService.Receipt.class),
                java.util.Map.entry("ExpenseSubmissionReceipt", io.agentflow.expense.ExpenseSubmissionService.Receipt.class),
                java.util.Map.entry("ExpensePaperReceipt", io.agentflow.expense.ExpenseApprovalService.Receipt.class),
                java.util.Map.entry("ExpenseLifecycleReceipt", io.agentflow.expense.ExpenseLifecycleService.Receipt.class),
                java.util.Map.entry("ExpensePrecheckReceipt", io.agentflow.expense.ExpensePrecheckService.Receipt.class),
                java.util.Map.entry("ExpensePrecheckOptions", io.agentflow.expense.ExpensePrecheckService.Options.class),
                java.util.Map.entry("ExpensePrecheckSummary", io.agentflow.expense.ExpensePrecheckService.Summary.class),
                java.util.Map.entry("ExpensePrecheckFinding", io.agentflow.expense.ExpensePrecheckJob.Finding.class),
                java.util.Map.entry("ExpensePrecheckView", io.agentflow.expense.ExpensePrecheckService.View.class),
                java.util.Map.entry("ExpensePrecheckPage", io.agentflow.expense.ExpensePrecheckService.Page.class),
                java.util.Map.entry("InvoiceVerificationReceipt", io.agentflow.expense.InvoiceVerificationService.Receipt.class),
                java.util.Map.entry("InvoiceVerificationOptions", io.agentflow.expense.InvoiceVerificationService.Options.class),
                java.util.Map.entry("InvoiceVerificationView", io.agentflow.expense.InvoiceVerificationService.View.class),
                java.util.Map.entry("InvoiceVerificationPage", io.agentflow.expense.InvoiceVerificationService.Page.class),
                java.util.Map.entry("InvoiceReceipt", io.agentflow.expense.InvoiceWalletService.Receipt.class),
                java.util.Map.entry("InvoiceOriginalMetadata", io.agentflow.expense.InvoiceWalletService.OriginalMetadata.class),
                java.util.Map.entry("InvoiceWalletItem", io.agentflow.expense.InvoiceWalletService.Item.class),
                java.util.Map.entry("InvoiceWalletPage", io.agentflow.expense.InvoiceWalletService.Page.class),
                java.util.Map.entry("InvoiceWalletOptions", io.agentflow.expense.InvoiceWalletService.Options.class),
                java.util.Map.entry("InvoiceFacts", io.agentflow.expense.Invoice.VerifiedFacts.class),
                java.util.Map.entry("InvoiceKey", io.agentflow.expense.InvoiceKey.class),
                java.util.Map.entry("ExpenseUse", io.agentflow.expense.ExpenseUse.class),
                java.util.Map.entry("FinanceCatalog", io.agentflow.finance.FinanceCatalog.class),
                java.util.Map.entry("FinanceLegalEntity", io.agentflow.finance.FinanceCatalog.LegalEntity.class),
                java.util.Map.entry("FinanceCategory", io.agentflow.finance.FinanceCatalog.Category.class),
                java.util.Map.entry("FinanceCostCenter", io.agentflow.finance.FinanceCatalog.CostCenter.class),
                java.util.Map.entry("FinanceProject", io.agentflow.finance.FinanceCatalog.Project.class),
                java.util.Map.entry("FinanceCity", io.agentflow.finance.FinanceCatalog.City.class),
                java.util.Map.entry("BusinessReference", io.agentflow.approval.model.BusinessReference.class),
                java.util.Map.entry("Money", io.agentflow.finance.Money.class),
                java.util.Map.entry("ExpenseContent", io.agentflow.expense.ExpenseContent.class),
                java.util.Map.entry("ExpenseLine", io.agentflow.expense.ExpenseLine.class),
                java.util.Map.entry("ExpensePolicySnapshot", io.agentflow.expense.ExpensePolicySnapshot.class),
                java.util.Map.entry("ExpensePolicySelection", io.agentflow.expense.ExpensePolicySelection.class),
                java.util.Map.entry("ExpensePolicyReceipt", io.agentflow.expense.ExpensePolicyReceipt.class),
                java.util.Map.entry("ExpenseCategoryDefinition", io.agentflow.expense.ExpenseCategoryCatalog.Category.class),
                java.util.Map.entry("ExpenseCategoryCatalog", io.agentflow.expense.ExpenseCategoryCatalog.class),
                java.util.Map.entry("ExpenseCategoryUpdate", io.agentflow.expense.ExpenseConfigurationInput.Categories.class),
                java.util.Map.entry("ExpenseCategoryRevision", io.agentflow.expense.JdbcExpenseConfigurationRepository.CategoryRevision.class),
                java.util.Map.entry("ExpenseCategorySummary", io.agentflow.expense.JdbcExpenseConfigurationRepository.CategorySummary.class),
                java.util.Map.entry("ExpenseCategoryPage", io.agentflow.expense.ExpenseConfigurationService.CategoryPage.class),
                java.util.Map.entry("ExpensePolicyDefinition", io.agentflow.expense.ExpensePolicyDefinition.class),
                java.util.Map.entry("ExpensePolicyRule", io.agentflow.expense.ExpensePolicyDefinition.Rule.class),
                java.util.Map.entry("ExpensePolicyMatch", io.agentflow.expense.ExpensePolicyDefinition.Match.class),
                java.util.Map.entry("ExpensePolicyConstraints", io.agentflow.expense.ExpensePolicyDefinition.Constraints.class),
                java.util.Map.entry("ExpensePolicyDraft", io.agentflow.expense.ExpensePolicyDraft.class),
                java.util.Map.entry("ExpensePolicyDraftSave", io.agentflow.expense.ExpenseConfigurationInput.Draft.class),
                java.util.Map.entry("ExpensePolicyPublish", io.agentflow.expense.ExpenseConfigurationInput.Publish.class),
                java.util.Map.entry("PublishedExpensePolicy", io.agentflow.expense.PublishedExpensePolicy.class),
                java.util.Map.entry("AccountMappingKey", io.agentflow.finance.AccountMappingPort.Key.class),
                java.util.Map.entry("AccountMappingEntry", io.agentflow.finance.AccountMappingPort.Entry.class),
                java.util.Map.entry("AccountMappingDefinition", io.agentflow.finance.AccountMappingDefinition.class),
                java.util.Map.entry("AccountMappingDraftSave", io.agentflow.finance.AccountMappingConfigurationInput.Draft.class),
                java.util.Map.entry("AccountMappingPublish", io.agentflow.finance.AccountMappingConfigurationInput.Publish.class),
                java.util.Map.entry("AccountMappingDraft", io.agentflow.finance.AccountMappingDraft.class),
                java.util.Map.entry("PublishedAccountMapping", io.agentflow.finance.PublishedAccountMapping.class),
                java.util.Map.entry("AccountMappingConfigurationCurrent", io.agentflow.finance.AccountMappingConfigurationService.Current.class),
                java.util.Map.entry("AccountMappingDraftSummary", io.agentflow.finance.JdbcAccountMappingRepository.DraftSummary.class),
                java.util.Map.entry("AccountMappingVersionSummary", io.agentflow.finance.JdbcAccountMappingRepository.VersionSummary.class),
                java.util.Map.entry("AccountMappingDraftRevision", io.agentflow.finance.JdbcAccountMappingRepository.DraftRevision.class),
                java.util.Map.entry("AccountMappingActivation", io.agentflow.finance.JdbcAccountMappingRepository.Activation.class),
                java.util.Map.entry("AccountMappingDraftPage", io.agentflow.finance.AccountMappingConfigurationService.DraftPage.class),
                java.util.Map.entry("AccountMappingVersionPage", io.agentflow.finance.AccountMappingConfigurationService.VersionPage.class),
                java.util.Map.entry("AccountMappingActivationPage", io.agentflow.finance.AccountMappingConfigurationService.ActivationPage.class),
                java.util.Map.entry("ExpenseConfigurationCurrent", io.agentflow.expense.ExpenseConfigurationService.Current.class),
                java.util.Map.entry("ExpensePolicyDraftSummary", io.agentflow.expense.JdbcExpenseConfigurationRepository.DraftSummary.class),
                java.util.Map.entry("ExpensePolicyDraftPage", io.agentflow.expense.ExpenseConfigurationService.DraftPage.class),
                java.util.Map.entry("ExpensePolicyVersionSummary", io.agentflow.expense.JdbcExpenseConfigurationRepository.VersionSummary.class),
                java.util.Map.entry("ExpensePolicyVersionPage", io.agentflow.expense.ExpenseConfigurationService.VersionPage.class),
                java.util.Map.entry("ExpensePolicyDraftRevision", io.agentflow.expense.JdbcExpenseConfigurationRepository.DraftRevision.class),
                java.util.Map.entry("ExpensePolicyActivation", io.agentflow.expense.JdbcExpenseConfigurationRepository.Activation.class),
                java.util.Map.entry("ExpensePolicyActivationPage", io.agentflow.expense.ExpenseConfigurationService.ActivationPage.class),
                java.util.Map.entry("ExpenseResponse", io.agentflow.expense.ExpenseResponse.class),
                java.util.Map.entry("ExpenseBudgetRetention", io.agentflow.expense.ExpenseResponse.BudgetRetention.class),
                java.util.Map.entry("ExpenseFinancialRound", io.agentflow.expense.ExpenseResponse.FinancialRound.class),
                java.util.Map.entry("CopySnapshot", io.agentflow.approval.copy.CopyReadService.Snapshot.class),
                java.util.Map.entry("AttachmentMetadata", io.agentflow.attachment.AttachmentService.Metadata.class),
                java.util.Map.entry("AttachmentOptions", io.agentflow.attachment.AttachmentService.Options.class),
                java.util.Map.entry("WebhookTarget", io.agentflow.integration.WebhookTargets.TargetView.class),
                java.util.Map.entry("WebhookDelivery", io.agentflow.integration.JdbcWebhookStore.Summary.class),
                java.util.Map.entry("WebhookPage", io.agentflow.integration.WebhookController.Page.class),
                java.util.Map.entry("WebhookAttempt", io.agentflow.integration.JdbcWebhookStore.Attempt.class),
                java.util.Map.entry("WebhookRetryRequest", io.agentflow.integration.JdbcWebhookStore.RetryRequest.class),
                java.util.Map.entry("WebhookDetail", io.agentflow.integration.WebhookController.Detail.class),
                java.util.Map.entry("RoundDiagram", io.agentflow.approval.history.RoundDiagramPort.Diagram.class),
                java.util.Map.entry("RoundCandidateSnapshot", io.agentflow.approval.history.RoundDiagramPort.CandidateSnapshot.class),
                java.util.Map.entry("RoundDiagramNode", io.agentflow.approval.history.RoundDiagramPort.Node.class),
                java.util.Map.entry("RoundDiagramEdge", io.agentflow.approval.history.RoundDiagramPort.Edge.class),
                java.util.Map.entry("AuditSearchItem", io.agentflow.approval.operations.AuditSearchPort.Item.class),
                java.util.Map.entry("AuditSearchPage", io.agentflow.approval.operations.AuditSearchController.Page.class),
                java.util.Map.entry("ApplicationSearchItem", io.agentflow.approval.operations.ApplicationSearchPort.Item.class),
                java.util.Map.entry("ApplicationSearchPage", io.agentflow.approval.operations.ApplicationSearchController.Page.class),
                java.util.Map.entry("BusinessCalendar", io.agentflow.calendar.BusinessCalendarController.CalendarResponse.class),
                java.util.Map.entry("CalendarSummary", io.agentflow.calendar.BusinessCalendarRepository.Summary.class),
                java.util.Map.entry("CalendarRules", io.agentflow.calendar.CalendarRules.class),
                java.util.Map.entry("CalendarPeriod", io.agentflow.calendar.CalendarRules.Period.class),
                java.util.Map.entry("CalendarOverride", io.agentflow.calendar.CalendarRules.DayOverride.class),
                java.util.Map.entry("CalendarPage", io.agentflow.calendar.BusinessCalendarService.CalendarPage.class),
                java.util.Map.entry("CalendarVersionPage", io.agentflow.calendar.BusinessCalendarService.VersionPage.class),
                java.util.Map.entry("CalendarCalculation", io.agentflow.calendar.BusinessCalendarService.Calculation.class),
                java.util.Map.entry("CalendarDeadline", io.agentflow.calendar.BusinessDeadline.Result.class),
                java.util.Map.entry("FirstWorkflowReport", io.agentflow.onboarding.FirstWorkflowReadPort.Report.class),
                java.util.Map.entry("FirstWorkflowDefinition", io.agentflow.onboarding.FirstWorkflowReadPort.Definition.class),
                java.util.Map.entry("FirstWorkflowEvidence", io.agentflow.onboarding.FirstWorkflowReadPort.Evidence.class),
                java.util.Map.entry("OperationsReport", io.agentflow.approval.operations.ApprovalOperationsReadPort.Report.class),
                java.util.Map.entry("OperationsMetrics", io.agentflow.approval.operations.ApprovalOperationsReadPort.Metrics.class),
                java.util.Map.entry("OperationsSlaMetrics", io.agentflow.approval.operations.ApprovalOperationsReadPort.SlaMetrics.class),
                java.util.Map.entry("OperationsNotificationMetrics", io.agentflow.approval.operations.ApprovalOperationsReadPort.NotificationMetrics.class),
                java.util.Map.entry("OperationsAgentMetrics", io.agentflow.approval.operations.ApprovalOperationsReadPort.AgentMetrics.class),
                java.util.Map.entry("OperationsDaily", io.agentflow.approval.operations.ApprovalOperationsReadPort.Daily.class),
                java.util.Map.entry("OperationsProcess", io.agentflow.approval.operations.ApprovalOperationsReadPort.ProcessSummary.class),
                java.util.Map.entry("OperationsWaitingNode", io.agentflow.approval.operations.ApprovalOperationsReadPort.WaitingNode.class),
                java.util.Map.entry("OperationsWaitingTask", io.agentflow.approval.operations.ApprovalOperationsReadPort.WaitingTask.class),
                java.util.Map.entry("AssigneeOption", io.agentflow.definition.DefinitionAssigneeDirectory.Option.class),
                java.util.Map.entry("ApplicationComment", io.agentflow.approval.comment.ApplicationComment.class),
                java.util.Map.entry("CommentPage", io.agentflow.approval.comment.ApplicationCommentService.Page.class),
                java.util.Map.entry("CommentMentionPage", io.agentflow.approval.comment.CommentMentionDirectory.Page.class),
                java.util.Map.entry("AssistReference", io.agentflow.agent.AssistInput.Reference.class),
                java.util.Map.entry("AssistSource", io.agentflow.agent.AssistModelPort.Source.class),
                java.util.Map.entry("AssistInputOptions", io.agentflow.agent.AssistExecutionService.InputOptions.class),
                java.util.Map.entry("AssistReceipt", io.agentflow.agent.AssistExecutionService.Receipt.class),
                java.util.Map.entry("AssistClaim", io.agentflow.agent.AssistSuggestion.Claim.class),
                java.util.Map.entry("AssistSuggestion", io.agentflow.agent.AssistSuggestion.class),
                java.util.Map.entry("AssistReview", io.agentflow.agent.AssistRun.Review.class),
                java.util.Map.entry("AssistRunItem", io.agentflow.agent.AssistRunReadPort.Item.class),
                java.util.Map.entry("AssistRunPage", io.agentflow.agent.AssistRunQueryService.Page.class),
                java.util.Map.entry("AssistRunDetail", io.agentflow.agent.AssistRunQueryService.Detail.class),
                java.util.Map.entry("Application", io.agentflow.approval.ApplicationResponse.class),
                java.util.Map.entry("SubmissionRound", io.agentflow.approval.SubmissionRoundResponse.class),
                java.util.Map.entry("InitiatorContext", io.agentflow.organization.InitiatorContext.class),
                java.util.Map.entry("Definition", io.agentflow.definition.DefinitionController.DefinitionResponse.class),
                java.util.Map.entry("DefinitionAvailabilityChange", io.agentflow.definition.DefinitionAvailabilityChange.class),
                java.util.Map.entry("DefinitionAvailabilityHistory", io.agentflow.definition.DefinitionAvailabilityController.HistoryPage.class),
                java.util.Map.entry("PublicationResult", io.agentflow.definition.DefinitionController.PublicationResponse.class),
                java.util.Map.entry("Publication", io.agentflow.definition.DefinitionPublication.class),
                java.util.Map.entry("ValidationResult", io.agentflow.definition.DefinitionController.ValidationResponse.class),
                java.util.Map.entry("BranchDiagnostic", io.agentflow.definition.BranchCoverageAnalyzer.Diagnostic.class),
                java.util.Map.entry("PublicationValidation", io.agentflow.definition.DefinitionPublication.ValidationSummary.class),
                java.util.Map.entry("Task", io.agentflow.approval.process.FlowableTaskFacade.TaskView.class),
                java.util.Map.entry("CountersignProgress", io.agentflow.approval.model.CountersignProgress.class),
                java.util.Map.entry("TaskActionResult", io.agentflow.approval.process.FlowableTaskFacade.ActionResult.class),
                java.util.Map.entry("PendingTask", io.agentflow.approval.workspace.PendingTaskReadPort.Item.class),
                java.util.Map.entry("PendingTaskPage", io.agentflow.approval.workspace.PendingTaskController.Page.class),
                java.util.Map.entry("WorkspaceApplication", io.agentflow.approval.workspace.WorkspaceReadPort.ApplicationItem.class),
                java.util.Map.entry("HandledItem", io.agentflow.approval.workspace.WorkspaceReadPort.HandledItem.class),
                java.util.Map.entry("InboxMessage", io.agentflow.notification.InboxMessage.class),
                java.util.Map.entry("VoucherNotificationTarget", io.agentflow.notification.VoucherNotificationAccess.Target.class),
                java.util.Map.entry("BudgetNotificationTarget", io.agentflow.notification.BudgetNotificationAccess.Target.class),
                java.util.Map.entry("SupplierReturnNotificationTarget", io.agentflow.notification.SupplierReturnNotificationAccess.Target.class),
                java.util.Map.entry("ExpenseReturnNotificationTarget", io.agentflow.notification.ExpenseReturnNotificationAccess.Target.class),
                java.util.Map.entry("DisbursementReturnNotificationTarget", io.agentflow.notification.DisbursementReturnNotificationAccess.Target.class),
                java.util.Map.entry("BudgetAdjustmentNotificationTarget", io.agentflow.notification.BudgetAdjustmentNotificationAccess.Target.class),
                java.util.Map.entry("SupplierPayableNotificationTarget", io.agentflow.notification.SupplierPayableNotificationAccess.Target.class),
                java.util.Map.entry("ExpensePartialAdjustmentNotificationTarget", io.agentflow.notification.ExpensePartialAdjustmentNotificationAccess.Target.class),
                java.util.Map.entry("ExpensePartialAdjustmentNotificationPreparation", io.agentflow.notification.ExpensePartialAdjustmentNotificationAccess.Preparation.class),
                java.util.Map.entry("ExpensePartialAdjustmentNotificationOperation", io.agentflow.notification.ExpensePartialAdjustmentNotificationAccess.Operation.class),
                java.util.Map.entry("ExpensePartialAdjustmentNotificationAdjustment", io.agentflow.notification.ExpensePartialAdjustmentNotificationAccess.Adjustment.class),
                java.util.Map.entry("ExpensePartialAdjustmentNotificationCompletion", io.agentflow.notification.ExpensePartialAdjustmentNotificationAccess.Completion.class),
                java.util.Map.entry("ExpensePartialAdjustmentNotificationRetirement", io.agentflow.notification.ExpensePartialAdjustmentNotificationAccess.Retirement.class),
                java.util.Map.entry("ExpensePartialAdjustmentNotificationResolution", io.agentflow.notification.ExpensePartialAdjustmentNotificationAccess.Resolution.class),
                java.util.Map.entry("ExpenseAdjustmentNotificationTarget", io.agentflow.notification.ExpenseAdjustmentNotificationAccess.Target.class),
                java.util.Map.entry("ExpenseAdjustmentNotificationPreparation", io.agentflow.notification.ExpenseAdjustmentNotificationAccess.Preparation.class),
                java.util.Map.entry("ExpenseAdjustmentNotificationBudget", io.agentflow.notification.ExpenseAdjustmentNotificationAccess.Budget.class),
                java.util.Map.entry("ExpenseAdjustmentNotificationAdjustment", io.agentflow.notification.ExpenseAdjustmentNotificationAccess.Adjustment.class),
                java.util.Map.entry("ExpenseAdjustmentNotificationCompletion", io.agentflow.notification.ExpenseAdjustmentNotificationAccess.Completion.class),
                java.util.Map.entry("ExpenseAdjustmentNotificationRetirement", io.agentflow.notification.ExpenseAdjustmentNotificationAccess.Retirement.class),
                java.util.Map.entry("BudgetAdjustmentNotificationReview", io.agentflow.notification.BudgetAdjustmentNotificationAccess.Review.class),
                java.util.Map.entry("SupplierPayableNotificationReview", io.agentflow.notification.SupplierPayableNotificationAccess.Review.class),
                java.util.Map.entry("BudgetAdjustmentNotificationOperation", io.agentflow.notification.BudgetAdjustmentNotificationAccess.Operation.class),
                java.util.Map.entry("SupplierPayableNotificationOperation", io.agentflow.notification.SupplierPayableNotificationAccess.Operation.class),
                java.util.Map.entry("BudgetAdjustmentNotificationObservation", io.agentflow.notification.BudgetAdjustmentNotificationAccess.Observation.class),
                java.util.Map.entry("SupplierPayableNotificationObservation", io.agentflow.notification.SupplierPayableNotificationAccess.Observation.class),
                java.util.Map.entry("BudgetAdjustmentNotificationRetirement", io.agentflow.notification.BudgetAdjustmentNotificationAccess.Retirement.class),
                java.util.Map.entry("SupplierPayableNotificationRetirement", io.agentflow.notification.SupplierPayableNotificationAccess.Retirement.class),
                java.util.Map.entry("RepaymentReviewNotificationTarget", io.agentflow.notification.RepaymentReviewNotificationAccess.Target.class),
                java.util.Map.entry("RepaymentReviewNotificationObservation", io.agentflow.notification.RepaymentReviewNotificationAccess.Observation.class),
                java.util.Map.entry("RepaymentReviewNotificationResolution", io.agentflow.notification.RepaymentReviewNotificationAccess.Resolution.class),
                java.util.Map.entry("RepaymentNotificationTarget", io.agentflow.notification.RepaymentNotificationAccess.Target.class),
                java.util.Map.entry("RepaymentNotificationObservation", io.agentflow.notification.RepaymentNotificationAccess.Observation.class),
                java.util.Map.entry("RepaymentNotificationRecord", io.agentflow.notification.RepaymentNotificationAccess.Registration.class),
                java.util.Map.entry("SupplierReturnNotificationObservation", io.agentflow.notification.SupplierReturnNotificationAccess.Observation.class),
                java.util.Map.entry("ExpenseReturnNotificationObservation", io.agentflow.notification.ExpenseReturnNotificationAccess.Observation.class),
                java.util.Map.entry("DisbursementReturnNotificationObservation", io.agentflow.notification.DisbursementReturnNotificationAccess.Observation.class),
                java.util.Map.entry("SupplierReturnNotificationRegistration", io.agentflow.notification.SupplierReturnNotificationAccess.Registration.class),
                java.util.Map.entry("ExpenseReturnNotificationRegistration", io.agentflow.notification.ExpenseReturnNotificationAccess.Registration.class),
                java.util.Map.entry("DisbursementReturnNotificationResolution", io.agentflow.notification.DisbursementReturnNotificationAccess.Resolution.class),
                java.util.Map.entry("SupplierAdjustmentNotificationTarget", io.agentflow.notification.SupplierAdjustmentNotificationAccess.Target.class),
                java.util.Map.entry("SupplierAdjustmentNotificationPreparation", io.agentflow.notification.SupplierAdjustmentNotificationAccess.Preparation.class),
                java.util.Map.entry("SupplierAdjustmentNotificationOperation", io.agentflow.notification.SupplierAdjustmentNotificationAccess.Operation.class),
                java.util.Map.entry("SupplierAdjustmentNotificationRetirement", io.agentflow.notification.SupplierAdjustmentNotificationAccess.Retirement.class),
                java.util.Map.entry("SupplierAdjustmentNotificationCompletion", io.agentflow.notification.SupplierAdjustmentNotificationAccess.Completion.class),
                java.util.Map.entry("SupplierSettlementNotificationTarget", io.agentflow.notification.SupplierSettlementNotificationAccess.Target.class),
                java.util.Map.entry("SupplierSettlementNotificationPreparation", io.agentflow.notification.SupplierSettlementNotificationAccess.Preparation.class),
                java.util.Map.entry("SupplierSettlementNotificationOperation", io.agentflow.notification.SupplierSettlementNotificationAccess.Operation.class),
                java.util.Map.entry("SupplierSettlementNotificationRetirement", io.agentflow.notification.SupplierSettlementNotificationAccess.Retirement.class),
                java.util.Map.entry("SupplierSettlementNotificationCompletion", io.agentflow.procurement.ProcurementPayableReservation.Settlement.class),
                java.util.Map.entry("ExpenseSettlementNotificationTarget", io.agentflow.notification.ExpenseSettlementNotificationAccess.Target.class),
                java.util.Map.entry("ExpenseSettlementNotificationState", io.agentflow.notification.ExpenseSettlementNotificationAccess.State.class),
                java.util.Map.entry("ReversalNotificationTarget", io.agentflow.notification.ReversalNotificationAccess.Target.class),
                java.util.Map.entry("ReversalCheckNotificationTarget", io.agentflow.notification.ReversalCheckNotificationAccess.Target.class),
                java.util.Map.entry("ReversalCheckNotificationObservation", io.agentflow.notification.ReversalCheckNotificationAccess.Observation.class),
                java.util.Map.entry("ReversalCheckNotificationRegistration", io.agentflow.notification.ReversalCheckNotificationAccess.Registration.class),
                java.util.Map.entry("ReversalNotificationPreparation", io.agentflow.notification.ReversalNotificationAccess.Preparation.class),
                java.util.Map.entry("ReversalNotificationOperation", io.agentflow.notification.ReversalNotificationAccess.Operation.class),
                java.util.Map.entry("ReversalNotificationRetirement", io.agentflow.notification.ReversalNotificationAccess.Retirement.class),
                java.util.Map.entry("InboxPage", io.agentflow.notification.InboxApplicationService.Page.class),
                java.util.Map.entry("NotificationPreferences", io.agentflow.notification.NotificationPreferencesController.View.class),
                java.util.Map.entry("HistoryEvent", io.agentflow.approval.history.HistoryEvent.class),
                java.util.Map.entry("HistoryPage", io.agentflow.approval.history.HistoryPage.class),
                java.util.Map.entry("AuthOptions", io.agentflow.auth.AuthController.AuthOptions.class),
                java.util.Map.entry("LoginResponse", io.agentflow.auth.AuthController.LoginResponse.class),
                java.util.Map.entry("CurrentIdentity", io.agentflow.auth.AuthService.LoginResult.class),
                java.util.Map.entry("SimulationResult", io.agentflow.definition.DefinitionSimulator.Result.class),
                java.util.Map.entry("FieldPreviewResult", io.agentflow.form.FormFieldProjection.class),
                java.util.Map.entry("SimulationDecision", io.agentflow.definition.DefinitionSimulator.Decision.class),
                java.util.Map.entry("SimulationBranch", io.agentflow.definition.DefinitionSimulator.Branch.class),
                java.util.Map.entry("ComparisonChange", io.agentflow.definition.DefinitionDiffService.Change.class),
                java.util.Map.entry("ComparisonBaseline", io.agentflow.definition.DefinitionApplicationService.Baseline.class),
                java.util.Map.entry("TemplateCopy", io.agentflow.template.TemplateCopyRepository.CopyView.class),
                java.util.Map.entry("TemplateScenario", io.agentflow.template.ProcessTemplate.Scenario.class),
                java.util.Map.entry("FormField", io.agentflow.form.FormSchema.Field.class),
                java.util.Map.entry("FormOption", io.agentflow.form.FormSchema.Option.class),
                java.util.Map.entry("GraphNode", io.agentflow.definition.DefinitionModels.Node.class),
                java.util.Map.entry("GraphEdge", io.agentflow.definition.DefinitionModels.Edge.class));
        types.forEach((name, type) -> {
            Set<String> fields = new HashSet<>(); spec.path("components").path("schemas").path(name).path("properties").fieldNames().forEachRemaining(fields::add);
            assertThat(fields).as("response fields for %s", name).isEqualTo(Arrays.stream(type.getRecordComponents())
                    .map(java.lang.reflect.RecordComponent::getName).collect(Collectors.toSet()));
        });
    }

    @Test
    void contractRequiresAuthenticationAndContainsNoSessionData() throws Exception {
        mvc.perform(get("/api/v1/openapi.json")).andExpect(status().isUnauthorized());
        String token = auth.login("demo", "alice", "demo").token();
        String body = mvc.perform(get("/api/v1/openapi.json").header("Authorization", "Bearer " + token))
                .andExpect(status().isOk()).andExpect(header().string("Cache-Control", "no-store"))
                .andExpect(content().contentTypeCompatibleWith("application/json"))
                .andExpect(jsonPath("openapi").value("3.1.1"))
                .andReturn().getResponse().getContentAsString(StandardCharsets.UTF_8);
        assertThat(body).doesNotContain(token);
        assertThat(json.read(body, JsonNode.class)).isEqualTo(document());
    }

    @Test
    void cancellationIsReadableForApplicationsAndSystemStoppedSubprocessRounds() throws Exception {
        JsonNode spec = document();
        for (var entry : java.util.Map.of("Application", "status", "WorkspaceApplication", "status", "HandledItem", "applicationStatus",
                "SubmissionRound", "status", "RoundDiagram", "status", "FirstWorkflowEvidence", "status").entrySet()) {
            var values = spec.path("components").path("schemas").path(entry.getKey()).path("properties").path(entry.getValue()).path("enum");
            assertThat(java.util.stream.StreamSupport.stream(values.spliterator(), false).map(JsonNode::asText)).contains("CANCELLED");
        }
    }

    private JsonNode resolve(JsonNode spec, JsonNode schema) {
        return schema.has("$ref") ? spec.at(schema.get("$ref").asText().substring(1)) : schema;
    }

    @Test
    void callbackContractAllowsAbsentOptionalFieldsFromTheRealSerializer() throws Exception {
        var schemas = document().path("components").path("schemas");
        var token = auth.login("demo", "admin", "demo").token();
        var response = mvc.perform(get("/api/v1/integrations/payment/callbacks").header("Authorization", "Bearer " + token))
                .andExpect(status().isOk()).andReturn().getResponse().getContentAsString();
        var page = json.read(response, JsonNode.class);
        schemas.path("PaymentCallbackPage").path("required").forEach(field ->
                assertThat(page.has(field.asText())).as("actual callback page includes required %s", field.asText()).isTrue());
        var now = java.time.Instant.parse("2026-09-29T10:00:00Z");
        var value = new io.agentflow.finance.callback.PaymentCallbackController.View(java.util.UUID.randomUUID(), "event-original",
                io.agentflow.finance.callback.PaymentCallbackVerifier.Kind.EMPLOYEE, java.util.UUID.randomUUID(), 1L, 1L,
                io.agentflow.finance.callback.PaymentCallback.Status.RECEIVED, now, now, now, 0, null, null, null, null);
        var wire = json.read(json.write(value), JsonNode.class);
        schemas.path("PaymentCallbackView").path("required").forEach(field ->
                assertThat(wire.has(field.asText())).as("serialized callback includes required %s", field.asText()).isTrue());
    }

    @Test
    void availabilityIsOptionalOnlyOnLegacyDefinitionWriteReplays() throws Exception {
        var schemas = document().path("components").path("schemas");
        assertThat(java.util.stream.StreamSupport.stream(schemas.path("Definition").path("required").spliterator(), false)
                .map(JsonNode::asText)).doesNotContain("startEnabled");
        assertThat(java.util.stream.StreamSupport.stream(schemas.path("DefinitionCatalogItem").path("required").spliterator(), false)
                .map(JsonNode::asText)).contains("startEnabled");
    }
}
