CREATE TABLE AF_HTTP_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL PRIMARY KEY,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(128)
);

CREATE UNIQUE INDEX AF_HTTP_SESSION_ID ON AF_HTTP_SESSION (SESSION_ID);
CREATE INDEX AF_HTTP_SESSION_EXPIRY ON AF_HTTP_SESSION (EXPIRY_TIME);
CREATE INDEX AF_HTTP_SESSION_PRINCIPAL ON AF_HTTP_SESSION (PRINCIPAL_NAME);

CREATE TABLE AF_HTTP_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BYTEA NOT NULL,
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES AF_HTTP_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
