CREATE TABLE AF_OIDC_LOGOUT_ORDER (
    ID INTEGER NOT NULL PRIMARY KEY CHECK (ID = 1),
    LAST_ORDER BIGINT NOT NULL
);
INSERT INTO AF_OIDC_LOGOUT_ORDER (ID, LAST_ORDER) VALUES (1, 0);

CREATE TABLE AF_OIDC_LOGOUT_EVENT (
    EVENT_HASH CHAR(64) NOT NULL PRIMARY KEY
);

ALTER TABLE AF_OIDC_LOGOUT_SCOPE ADD COLUMN LOGOUT_ORDER BIGINT NOT NULL DEFAULT 0;
